### PR TITLE
Update OLM plugin dev documentation; simplify monitored operators init

### PR DESCRIPTION
**Pull request by jakub-dzon**
This PR introduces two changes:
 - simplification of monitored operators initialization in `operators.Manager` builder;
 - update of the OLM operator plugin development documentation due to changes introduced in #1094.

### CODE REVIEW

**Comment by jakub-dzon** [comment]
@YuviGold - please have a look

**Review by YuviGold — APPROVED** [review]
Looks good :)

**Comment by YuviGold** [comment]
/hold
seems you have a conflict on generation
```
08:35:43  ../../operators/builder.go:26:102: cannot use cnv.NewCNVOperator(log) (type *cnv.operator) as type api.Operator in argument to NewManagerWithOperators:
08:35:43  	*cnv.operator does not implement api.Operator (missing GetMonitoredOperator method)
08:35:44  # github.com/openshift/****-service/internal/operators
08:35:44  ../../operators/builder.go:26:102: cannot use cnv.NewCNVOperator(log) (type *cnv.operator) as type api.Operator in argument to NewManagerWithOperators:
08:35:44  	*cnv.operator does not implement api.Operator (missing GetMonitoredOperator method)
08:35:44  prog.go:12:2: cannot find module providing package github.com/golang/mock/mockgen/model: working directory is not part of a module
08:35:44  prog.go:14:2: cannot find module providing package github.com/openshift/****-service/internal/bminventory: working directory is not part of a module
08:35:44  2021/03/07 06:35:44 Loading input failed: exit status 1
08:35:44  internal/bminventory/inventory.go:290: running "mockgen": exit status 1
08:35:51  # github.com/openshift/****-service/internal/operators
08:35:51  ../../operators/builder.go:26:102: cannot use cnv.NewCNVOperator(log) (type *cnv.operator) as type api.Operator in argument to NewManagerWithOperators:
08:35:51  	*cnv.operator does not implement api.Operator (missing GetMonitoredOperator method)
08:35:51  # github.com/openshift/****-service/internal/operators
08:35:51  ../../operators/builder.go:26:102: cannot use cnv.NewCNVOperator(log) (type *cnv.operator) as type api.Operator in argument to NewManagerWithOperators:
08:35:51  	*cnv.operator does not implement api.Operator (missing GetMonitoredOperator method)
08:35:51  prog.go:12:2: cannot find module providing package github.com/golang/mock/mockgen/model: working directory is not part of a module
08:35:51  prog.go:14:2: cannot find module providing package github.com/openshift/****-service/internal/host: working directory is not part of a module
08:35:51  2021/03/07 06:35:51 Loading input failed: exit status 1
08:35:51  internal/host/host.go:89: running "mockgen": exit status 1
08:36:09  # github.com/openshift/****-service/internal/operators
08:36:09  ../builder.go:26:102: cannot use cnv.NewCNVOperator(log) (type *cnv.operator) as type api.Operator in argument to NewManagerWithOperators:
08:36:09  	*cnv.operator does not implement api.Operator (missing GetMonitoredOperator method)
08:36:09  # github.com/openshift/****-service/internal/operators
08:36:09  ../builder.go:26:102: cannot use cnv.NewCNVOperator(log) (type *cnv.operator) as type api.Operator in argument to NewManagerWithOperators:
08:36:09  	*cnv.operator does not implement api.Operator (missing GetMonitoredOperator method)
08:36:09  prog.go:12:2: cannot find module providing package github.com/golang/mock/mockgen/model: working directory is not part of a module
08:36:09  prog.go:14:2: cannot find module providing package github.com/openshift/****-service/internal/operators: working directory is not part of a module
```

**Comment by jakub-dzon** [comment]
@YuviGold - thanks for checking on the issue! Fixed
/unhold
